# mm-inventory/docker-compose.yml

services:
  db:
    image: postgres:latest
    container_name: mm-inventory-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: marketmaster
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/mm-inventory.sql:/docker-entrypoint-initdb.d/mm-inventory.sql
    ports:
      - "5436:5432"
    networks:
      - marketmaster-network

  product_service:
    build: .
    container_name: mm-inventory
    ports:
      - "5705:5705"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    volumes:
      - .:/app
    networks:
      - marketmaster-network

volumes:
  postgres_data:

networks:
  marketmaster-network:
    external: true
